# global properties for all jack clients
jack.properties = {
     node.latency       = 512/48000
     node.rate          = 1/48000
     node.quantum       = 512/48000
     #node.lock-quantum  = true
     #node.force-quantum = 0
     #jack.show-monitor  = true
     #jack.merge-monitor = true
     #jack.show-midi     = true
     #jack.short-name    = false
     #jack.filter-name   = false
     #jack.filter-char   = " "
     #
     # allow:           Don't restrict self connect requests
     # fail-external:   Fail self connect requests to external ports only
     # ignore-external: Ignore self connect requests to external ports only
     # fail-all:        Fail all self connect requests
     # ignore-all:      Ignore all self connect requests
     #jack.self-connect-mode = allow
     #
     # allow:           Allow connect request of other ports
     # fail:            Fail connect requests of other ports
     # ignore:          Ignore connect requests of other ports
     #jack.other-connect-mode = allow
     #jack.locked-process    = true
     #jack.default-as-system = false
     #jack.fix-midi-events   = true
     #jack.global-buffer-size = false
     #jack.max-client-ports   = 768
     #jack.fill-aliases       = false
     #jack.writable-input     = true
     #jack.flag-midi2         = false
}

