# client specific properties
alsa.rules = [
    {
        matches = [ { application.process.binary = "resolve"  } ]
        actions = {
            update-props = {
                alsa.buffer-bytes = 131072
            }
        }

    }
]
