context.modules = [
    # Uses realtime scheduling to boost the audio thread priorities.
    { name = libpipewire-module-rt
        args = {
            nice.level = -20
            rt.prio = 99
            rt.time.soft = 200000
            rt.time.hard = 200000
        }
    }
]
